### ISSUE TITLE
auth doesnt work with newer keys

### ISSUE THREAD

**Issue by dantrevino** [MichaelFedora/mercurius#19]
Users with newer 24-word keys are unable to use the app.

**Comment by MichaelFedora** [comment]
currently it uses bip39 to validate mnemonics (see [util.ts](https://github.com/MichaelFedora/mercurius/blob/18558419b9df6a593e9a5c595c247d0678370069/src/util/util.ts#L23) & [login.ts](https://github.com/MichaelFedora/mercurius/blob/18558419b9df6a593e9a5c595c247d0678370069/src/components/mercurius-login/mercurius-login.ts#L51), is there are new library/key type that was implemented?

I haven't touched this code for almost two years so things are bound to break if I try to update it... you want to try to fork it & do a pr?

**Comment by dantrevino** [comment]
That was the first thing I did.  I was hoping you might have better luck .

**Comment by MichaelFedora** [comment]
do you think you could generate a sample key code for me to test?

**Comment by MichaelFedora** [comment]
I updated, please test when you can @dantrevino

**Comment by dantrevino** [comment]
I have a user who is looking for this. I've passed it on for him to test.

**Comment by MichaelFedora** [comment]
Closed due to inactivity 😔
